repos:
  - repo: https://github.com/savonet/pre-commit-ocamlformat
    rev: v1.0.0
    hooks:
      - id: ocamlformat
  - repo: https://github.com/google/yamlfmt
    rev: v0.9.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.3
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: no-commit-to-branch
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: [--contrib=CT1, --ignore=B6, --msg-filename]
        stages: [commit-msg]
