name: Docs
on:
  push:
    branches:
      - main
jobs:
  deploy-doc:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.0
          dune-cache: true
      - uses: ocaml/setup-ocaml/deploy-doc@v2
